#!/usr/bin/python
import os
print("cat /proc/cmdline")
os.system("cat /proc/cmdline")
print("cat /proc/version")
os.system("cat /proc/version")
print("uname -a")
os.system("uname -a")
print("df -h")
os.system("df -h")
print("timeout 5 ping www.baidu.com")
os.system("timeout 5 ping www.baidu.com")
print("fdisk -l")
os.system("fdisk -l")
print("mkfs.ext4")
os.system("mkfs.ext4")
print("apt-get install -y tree")
os.system("apt-get install -y tree")
